blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/mkshb/hass-maico-kwl/discussions
    about: Ask how to set something up, share your dashboard or discuss an idea.
