import type { HomeAssistant } from "./types";

export const STRINGS = {
  en: {
    card_name: "Maico KWL",
    card_description: "Airflow, temperatures and controls of a Maico ventilation unit.",
    no_device: "No Maico KWL unit found.",
    device_missing: "The selected unit no longer exists.",
    editor_device: "Unit",
    group_airflow: "Airflow",
    group_room: "Room",
    group_controls: "Controls",
    group_filters: "Filters",
    group_status: "Status",
    outdoor_air: "Outdoor air",
    supply_air: "Supply air",
    extract_air: "Extract air",
    exhaust_air: "Exhaust air",
    bypass_open: "Bypass open",
    bypass_closed: "Bypass closed",
    heat_recovery: "Heat recovery",
    fan_off: "off",
    ptc_heater: "PTC heater",
    tile_room: "Room",
    tile_humidity: "Humidity",
    tile_air_quality: "Air quality",
    tile_heat_recovery: "Heat recovery",
    bus_badge: "BUS",
    from_source: "from {name}",
    bus_stale: "no value for {minutes} min",
    no_value: "no value",
    sub_extract_air: "extract air",
    sub_external_sensor: "external sensor",
    air_good: "good",
    air_moderate: "moderate",
    air_poor: "poor",
    absolute_humidity_extract: "Absolute humidity of the extract air",
    energy_today: "{value} today",
    ventilation_level: "Ventilation level",
    operating_mode: "Operating mode",
    boost: "Boost",
    level_off: "Off",
    level_humidity_protection: "Humidity",
    level_reduced: "Reduced",
    level_nominal: "Nominal",
    level_intensive: "Intensive",
    level_auto_hint: "Level is chosen by {mode}",
    level_off_hint: "The unit is off",
    level_boost_hint: "Boost is running",
    filter_device: "Device filter",
    filter_outdoor: "Outdoor filter",
    filter_room: "Room filter",
    filter_days: "{days} days",
    filter_due: "due",
    filter_next_change: "Next change on {date}",
    notices_one: "1 notice",
    notices_many: "{count} notices",
    faults_one: "Fault",
    faults_many: "{count} faults",
  },
  de: {
    card_name: "Maico KWL",
    card_description: "Luftströme, Temperaturen und Bedienung eines Maico-Lüftungsgeräts.",
    no_device: "Kein Maico-KWL-Gerät gefunden.",
    device_missing: "Das gewählte Gerät gibt es nicht mehr.",
    editor_device: "Gerät",
    group_airflow: "Luftstrom",
    group_room: "Raum",
    group_controls: "Bedienung",
    group_filters: "Filter",
    group_status: "Status",
    outdoor_air: "Außenluft",
    supply_air: "Zuluft",
    extract_air: "Abluft",
    exhaust_air: "Fortluft",
    bypass_open: "Bypass offen",
    bypass_closed: "Bypass zu",
    heat_recovery: "Rückgewinnung",
    fan_off: "aus",
    ptc_heater: "PTC-Heizregister",
    tile_room: "Raum",
    tile_humidity: "Feuchte",
    tile_air_quality: "Luftgüte",
    tile_heat_recovery: "Rückgewinnung",
    bus_badge: "BUS",
    from_source: "von {name}",
    bus_stale: "seit {minutes} min kein Wert",
    no_value: "kein Wert",
    sub_extract_air: "Abluft",
    sub_external_sensor: "externer Fühler",
    air_good: "gut",
    air_moderate: "mäßig",
    air_poor: "schlecht",
    absolute_humidity_extract: "Absolute Feuchte Abluft",
    energy_today: "heute {value}",
    ventilation_level: "Lüftungsstufe",
    operating_mode: "Betriebsart",
    boost: "Stoßlüftung",
    level_off: "Aus",
    level_humidity_protection: "Feuchte",
    level_reduced: "Reduziert",
    level_nominal: "Nenn",
    level_intensive: "Intensiv",
    level_auto_hint: "Stufe wird von {mode} gewählt",
    level_off_hint: "Das Gerät ist aus",
    level_boost_hint: "Stoßlüftung läuft",
    filter_device: "Gerätefilter",
    filter_outdoor: "Außenluftfilter",
    filter_room: "Raumfilter",
    filter_days: "{days} Tage",
    filter_due: "fällig",
    filter_next_change: "Nächster Wechsel am {date}",
    notices_one: "1 Hinweis",
    notices_many: "{count} Hinweise",
    faults_one: "Störung",
    faults_many: "{count} Störungen",
  },
} as const;

export type StringKey = keyof (typeof STRINGS)["en"];

export function localize(
  hass: HomeAssistant | undefined,
  key: StringKey,
  values: Record<string, string | number> = {},
): string {
  const language = (hass?.locale?.language ?? hass?.language ?? "en").split("-")[0];
  const strings: Record<StringKey, string> =
    language in STRINGS ? STRINGS[language as keyof typeof STRINGS] : STRINGS.en;
  return strings[key].replace(/\{(\w+)\}/g, (match, name: string) =>
    name in values ? String(values[name]) : match,
  );
}

/** For the card picker, before any hass object exists. */
export function browserLocalize(key: StringKey): string {
  const language = navigator.language.split("-")[0];
  return (language in STRINGS ? STRINGS[language as keyof typeof STRINGS] : STRINGS.en)[key];
}
